### PR TITLE
🔀 Merge Jupyter book and Minimal Mistakes into single site

### PR DESCRIPTION
**Pull request by shnizzedy**
## Resolves

Resolves https://github.com/nmind/hackathon2021/issues/15 by @poldrack 
Resolves #13 by @shnizzedy 
Related to #1 by @poldrack & @paul-reiners
Related to https://github.com/nmind/nmind.github.io/pull/13#issuecomment-934664647 by @gkiar

## Description

We had two parallel website development streams: a Jekyll site (which is live at nmind.org) and a Jupyter book. This PR keeps the live Jekyll site at nmind.org, publishes the Jupyter book at nmind.org/book, and adds links to the Jupyter book to the header and footer of the Jekyll site.

## Technical details

* This structure necessitates a source branch and a publishing branch. I've set these up as `main` and `gh-pages` respectively, but we can make adjustments to the GitHub workflow script if we want to use different names.
* All of the Jupyter book content is in the `jupyter-book` directory in the source branch. All of the Jekyll content is in the root of the source branch.
* I split the README and similar files into three places: the project root for NMIND, `minimal-mistakes` for the Jekyll theme, and `jupyter-book` for the Jupyter book.
* GitHub Actions builds the Jupyter book to HTML, copies it into the Jekyll source, then builds the whole site from the Jekyll source.

### new links in header and footer
nmind.org
### Jupyter book
landing-page
example page
example notebook

### CODE REVIEW

**Comment by shnizzedy** [comment]
> - [ ] Do we want to set up an NMIND machine user to handle CI deployments? If so, how do we manage who has access to / control over said machine user?

― https://github.com/nmind/nmind.github.io/pull/13#issue-987866496

I set the [Computational Neuroimaging Lab's machine user](https://github.com/ChildMindInstituteCNL) as the user for publishing from the CI for now, but I'll open an issue for want entity we want to publish with long-term.

**Comment by gkiar** [comment]
Cool! @shnizzedy can you remind me what we are planning to have in the Jupyter book? Will it be a user-guide for the certification standards, or something else? I don't think we want a link in the header yet since it's currently so bare-bones, and perhaps the footer link should instead read "NMIND Guidebook" or something, since the fact that it's built in Jupyter isn't the most relevant to visitors? Happy to sync up on slack if that's easier :smile:

**Comment by shnizzedy** [comment]
@gkiar 

> can you remind me what we are planning to have in the Jupyter book? Will it be a user-guide for the certification standards, or something else?

:sweat_smile: I really don't know! When I asked 

> Do we benefit enough from each framework to justify the added complexity of maintaining both?
Presently, there's basically no content in the Jupyter Book, but I can see the potential.

― https://github.com/nmind/nmind.github.io/pull/13#issue-987866496

and @ericearl added

> Can someone summarize the idea of the NMIND Book?

― https://github.com/nmind/nmind.github.io/pull/13#issuecomment-912614239

you responded

> the purpose is really to have documentation that builds nicely from code, can be interactive, pretty, easily navigable, etc... I could see it being very valuable once our standards are defined more clearly, because code blocks and checklists seem a bit more manageable in the Jupyter book context.

― https://github.com/nmind/nmind.github.io/pull/13#issuecomment-934664647

which convinced me it was worth setting up. @poldrack & @satra might have more insight? I believe the Jupyter book conversation (on GitHub) began in https://github.com/nmind/hackathon2021/issues/15 and continued in https://github.com/nmind/nmind.github.io/pull/1 and https://github.com/nmind/nmind.github.io/pull/13 before getting to this PR

---

> I don't think we want a link in the header yet since it's currently so bare-bones, and perhaps the footer link should instead read "NMIND Guidebook" or something, since the fact that it's built in Jupyter isn't the most relevant to visitors?

I commented out the links in both the header and footer in db85513. I think it makes more sense to keep it orphaned (you would still be able to navigate to [nmind.org/book](https://nmind.org/book) to get to what little there is there, and the infrastructure would be set up so that all one would need to do to add to the book is add / update `*.ipynb` & `*.md` files in `jupyter-book/site` + update `jupyter-book/site/_toc.yml` as needed

**Comment by gkiar** [comment]
Thanks, @shnizzedy ! That was a helpful recap :+1: 

Ok, let's merge this now that it is orphaned, and, indeed, we can link to it from anywhere in the site when it becomes relevant, or just leave it on its own as a very underwhelming easter egg :egg:

**Pull request merged**
