### PR TITLE
Governance

### PR DESCRIPTION
**Pull request by gkiar**
## Description

Adds a description of the governance details and current leadership/members.

Aside: @shnizzedy should we do PRs to main or gh-pages?

### CODE REVIEW

**Comment by shnizzedy** [comment]
> Aside: @shnizzedy should we do PRs to main or gh-pages?

[`main`](https://github.com/nmind/nmind.github.io/blob/main/CONTRIBUTING.md#contributing-guidelines)

**Comment by gkiar** [comment]
OK wonderful, thanks! Q, then...

From when you merged the two distinct sites a while back, it seems there are a few file deletions I didn't expect (like PR template). Is that expected/what should I do to fix it if not?

Thanks!

**Comment by shnizzedy** [comment]
> From when you merged the two distinct sites a while back, it seems there are a few file deletions I didn't expect (like PR template). Is that expected/what should I do to fix it if not?

Not expected (I think)? I don't see any deletions [in the diff](https://github.com/nmind/nmind.github.io/pull/22/files) and [the PR template seems to be intact here](https://github.com/nmind/nmind.github.io/blob/main/.github/PULL_REQUEST_TEMPLATE.md). Unless you mean in the `gh-pages` branch, in which case, that _is_ expected ― that branch should just be what is served on [nmind.org](https://nmind.org)

**Comment by shnizzedy** [comment]
Oh, or do you mean the deletions in this PR? You could just rebase or cherry-pick your changes onto `main` and force-push on this branch (or I can do that tomorrow)

**Review by shnizzedy — APPROVED** [review]
lgtm!

**Pull request merged**
